//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Address_ID { get; set; }
        public Nullable<int> Party_ID { get; set; }
        public string LineOne { get; set; }
        public string LineTwo { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public string CityPrimary { get; set; }
    }
}
