//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterGroupLoggedReason
    {
        public int MasterGroupLoggedReason_ID { get; set; }
        public Nullable<int> MasterGroup_ID { get; set; }
        public string Reason { get; set; }
    }
}
