//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ca_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyBlob
    {
        public int PartyBlob_ID { get; set; }
        public int Party_ID { get; set; }
        public Nullable<int> BlobType_ID { get; set; }
        public string Name { get; set; }
        public string Blob { get; set; }
    }
}
